name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  cloud_firestore: ^6.7.1
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  random_string: 
  shared_preferences: 
  http:
  razorpay_flutter: ^1.3.5
  url_launcher: ^6.3.0
  intl: ^0.20.3
  pinput: ^5.0.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4  # Un-indented to sit under dev_dependencies
  flutter_lints: ^6.0.0

# ----------------------------------------------------
# APP ICON CONFIGURATION
# ----------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png" # Replace 'logo.png' with your actual icon file name
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - images/